### ISSUE TITLE
Systemd Service Type should be forking

### ISSUE THREAD

**Issue by reinhardt1053** [PacktPublishing/Delphi-Cookbook-Third-Edition#1]
Delphi-Cookbook-Third-Edition/Chapter07/CODE/RECIPE03_daemon_fork/consoled.service

Type should be forking because systemd considers the service started up once the process forks and the parent has exited. PIDFile should be also specified as well so systemd can keep track of the main process.

[1] https://wiki.archlinux.org/index.php/Systemd

**Comment by danieleteti** [comment]
Hi, thank you for your note. In the modern systemd the forking is now 100% handled by the systemd environment so there is really no need to do anything in that arena.

Some notes about the topic [here](https://jdebp.uk/FGA/unix-daemon-design-mistakes-to-avoid.html)

**Comment by YogineeMarathe** [comment]
Thank you for giving a note. As solution is given closing the issue.
